/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AnalyzeRouteImport } from './routes/analyze'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as SavedRouteImport } from './routes/saved'
import { Route as ApiAnalyzeRouteImport } from './routes/api/analyze'
import { Route as ApiDemoAnalysisRouteImport } from './routes/api/demo-analysis'
import { Route as ApiRecentReposRouteImport } from './routes/api/recent-repos'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyzeRoute = AnalyzeRouteImport.update({
  id: '/analyze',
  path: '/analyze',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const SavedRoute = SavedRouteImport.update({
  id: '/saved',
  path: '/saved',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAnalyzeRoute = ApiAnalyzeRouteImport.update({
  id: '/api/analyze',
  path: '/api/analyze',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDemoAnalysisRoute = ApiDemoAnalysisRouteImport.update({
  id: '/api/demo-analysis',
  path: '/api/demo-analysis',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRecentReposRoute = ApiRecentReposRouteImport.update({
  id: '/api/recent-repos',
  path: '/api/recent-repos',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/analyze': typeof AnalyzeRoute
  '/auth': typeof AuthRoute
  '/saved': typeof SavedRoute
  '/api/analyze': typeof ApiAnalyzeRoute
  '/api/demo-analysis': typeof ApiDemoAnalysisRoute
  '/api/recent-repos': typeof ApiRecentReposRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/analyze': typeof AnalyzeRoute
  '/auth': typeof AuthRoute
  '/saved': typeof SavedRoute
  '/api/analyze': typeof ApiAnalyzeRoute
  '/api/demo-analysis': typeof ApiDemoAnalysisRoute
  '/api/recent-repos': typeof ApiRecentReposRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/analyze': typeof AnalyzeRoute
  '/auth': typeof AuthRoute
  '/saved': typeof SavedRoute
  '/api/analyze': typeof ApiAnalyzeRoute
  '/api/demo-analysis': typeof ApiDemoAnalysisRoute
  '/api/recent-repos': typeof ApiRecentReposRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/analyze'
    | '/auth'
    | '/saved'
    | '/api/analyze'
    | '/api/demo-analysis'
    | '/api/recent-repos'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/analyze'
    | '/auth'
    | '/saved'
    | '/api/analyze'
    | '/api/demo-analysis'
    | '/api/recent-repos'
  id:
    | '__root__'
    | '/'
    | '/analyze'
    | '/auth'
    | '/saved'
    | '/api/analyze'
    | '/api/demo-analysis'
    | '/api/recent-repos'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AnalyzeRoute: typeof AnalyzeRoute
  AuthRoute: typeof AuthRoute
  SavedRoute: typeof SavedRoute
  ApiAnalyzeRoute: typeof ApiAnalyzeRoute
  ApiDemoAnalysisRoute: typeof ApiDemoAnalysisRoute
  ApiRecentReposRoute: typeof ApiRecentReposRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analyze': {
      id: '/analyze'
      path: '/analyze'
      fullPath: '/analyze'
      preLoaderRoute: typeof AnalyzeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/saved': {
      id: '/saved'
      path: '/saved'
      fullPath: '/saved'
      preLoaderRoute: typeof SavedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/analyze': {
      id: '/api/analyze'
      path: '/api/analyze'
      fullPath: '/api/analyze'
      preLoaderRoute: typeof ApiAnalyzeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/demo-analysis': {
      id: '/api/demo-analysis'
      path: '/api/demo-analysis'
      fullPath: '/api/demo-analysis'
      preLoaderRoute: typeof ApiDemoAnalysisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/recent-repos': {
      id: '/api/recent-repos'
      path: '/api/recent-repos'
      fullPath: '/api/recent-repos'
      preLoaderRoute: typeof ApiRecentReposRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AnalyzeRoute: AnalyzeRoute,
  AuthRoute: AuthRoute,
  SavedRoute: SavedRoute,
  ApiAnalyzeRoute: ApiAnalyzeRoute,
  ApiDemoAnalysisRoute: ApiDemoAnalysisRoute,
  ApiRecentReposRoute: ApiRecentReposRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
